// <auto-generated />
using System;
using CareerHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerHub.Api.Migrations
{
    [DbContext(typeof(CareerHubDbContext))]
    [Migration("20260604185246_FixedForeignKeysBaseline")]
    partial class FixedForeignKeysBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerHub.Api.Models.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("applicants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Email = "applicantA@test.com",
                            FullName = "Applicant A"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Email = "applicantB@test.com",
                            FullName = "Applicant B"
                        });
                });

            modelBuilder.Entity("CareerHub.Api.Models.Application", b =>
                {
                    b.Property<Guid>("JobListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobListingId", "ApplicantId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("CareerHub.Api.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("75ba7d3e-2b50-4841-860e-cbfb4e54e4df"),
                            Name = "TechCorp",
                            Website = "techcorp.com"
                        },
                        new
                        {
                            Id = new Guid("2d5d8e24-9b16-4d2a-89a1-fbf22d4f5c92"),
                            Name = "FinanceFlow",
                            Website = "financeflow.com"
                        },
                        new
                        {
                            Id = new Guid("a43fa893-7c3e-4b72-ac2b-923fca8565b3"),
                            Name = "HealthNet",
                            Website = "healthnet.com"
                        },
                        new
                        {
                            Id = new Guid("b11c34ef-56d1-419a-9cb8-b2a1aefb23d4"),
                            Name = "EduBuild",
                            Website = "edubuild.com"
                        },
                        new
                        {
                            Id = new Guid("e8fa4292-1a4b-4b11-bdc1-42cb9fa234fe"),
                            Name = "LogiRoute",
                            Website = "logiroute.com"
                        });
                });

            modelBuilder.Entity("CareerHub.Api.Models.JobListing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Title", "CompanyId")
                        .IsUnique();

                    b.ToTable("job_listings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("91111111-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("75ba7d3e-2b50-4841-860e-cbfb4e54e4df"),
                            Description = "C# Engineer needed",
                            IsActive = true,
                            Location = "Remote",
                            PostedAt = new DateTime(2026, 6, 2, 22, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Backend Developer",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("92222222-2222-2222-2222-222222222222"),
                            CompanyId = new Guid("2d5d8e24-9b16-4d2a-89a1-fbf22d4f5c92"),
                            Description = "SQL expert needed",
                            IsActive = true,
                            Location = "Cape Town",
                            PostedAt = new DateTime(2026, 6, 2, 22, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Data Analyst",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("93333333-3333-3333-3333-333333333333"),
                            CompanyId = new Guid("a43fa893-7c3e-4b72-ac2b-923fca8565b3"),
                            Description = "Docker expert",
                            IsActive = true,
                            Location = "Remote",
                            PostedAt = new DateTime(2026, 6, 2, 22, 0, 0, 0, DateTimeKind.Utc),
                            Title = "DevOps Specialist",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("94444444-4444-4444-4444-444444444444"),
                            CompanyId = new Guid("b11c34ef-56d1-419a-9cb8-b2a1aefb23d4"),
                            Description = "React components",
                            IsActive = true,
                            Location = "Johannesburg",
                            PostedAt = new DateTime(2026, 6, 2, 22, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Frontend Developer",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("95555555-5555-5555-5555-555555555555"),
                            CompanyId = new Guid("e8fa4292-1a4b-4b11-bdc1-42cb9fa234fe"),
                            Description = "AWS infra design",
                            IsActive = true,
                            Location = "Remote",
                            PostedAt = new DateTime(2026, 6, 2, 22, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Cloud Architect",
                            Type = 0
                        });
                });

            modelBuilder.Entity("CareerHub.Api.Models.Application", b =>
                {
                    b.HasOne("CareerHub.Api.Models.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerHub.Api.Models.JobListing", "JobListing")
                        .WithMany("Applications")
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobListing");
                });

            modelBuilder.Entity("CareerHub.Api.Models.JobListing", b =>
                {
                    b.HasOne("CareerHub.Api.Models.Company", "Company")
                        .WithMany("JobListings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CareerHub.Api.Models.Applicant", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("CareerHub.Api.Models.Company", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("CareerHub.Api.Models.JobListing", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
